spring.application.name=api_clientes

server.port=8081

datasource.host=jdbc:postgresql://localhost:5432/bd_api_clientes
datasource.user=postgres
datasource.pass=root

cors.enable=http://localhost:4200